services:
  - type: web
    name: iplogger
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_USE_SECURE_COOKIES
        value: "True"
      - key: DJANGO_TRUSTED_PROXY_HOPS
        value: "1"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: iplogger-db
          property: connectionString
databases:
  - name: iplogger-db
    plan: free
