services:
  - type: web
    name: iplogger
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "bash start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.10"
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_USE_SECURE_COOKIES
        value: "False"
      - key: DJANGO_FORCE_HTTPS
        value: "False"
      - key: DJANGO_USE_WHITENOISE
        value: "True"
      - key: DJANGO_TRUSTED_PROXY_HOPS
        value: "1"
      - key: DJANGO_IGNORED_USER_AGENTS
        value: "UptimeRobot"
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
